=== achmadf23/Tugas_2-/Pendidkan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="loginstaffpendidikan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dosen"/>
                <xs:element ref="mahasiswa"/>
                <xs:element ref="teknisi"/>
                <xs:element ref="satpam"/>
                <xs:element ref="pemilikkantin"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dosen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="namadosen"/>
                <xs:element ref="nikdosen"/>
                <xs:element ref="alamat"/>
                <xs:element ref="kota"/>
                <xs:element ref="jk"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="tl"/>
                <xs:element ref="email"/>
                <xs:element ref="kewarganegaraan"/>
                <xs:element ref="tahunkerja"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="namadosen" type="xs:NCName"/>
    <xs:element name="nikdosen" type="xs:integer"/>
    <xs:element name="kota" type="xs:NCName"/>
    <xs:element name="kewarganegaraan" type="xs:NCName"/>
    <xs:element name="tahunkerja" type="xs:integer"/>
    <xs:element name="mahasiswa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="namamahasiswa"/>
                <xs:element ref="alamat"/>
                <xs:element ref="kontak"/>
                <xs:element ref="jk"/>
                <xs:element ref="agama"/>
                <xs:element ref="status"/>
                <xs:element ref="tl"/>
                <xs:element ref="email"/>
                <xs:element ref="umur"/>
                <xs:element ref="jurusan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="namamahasiswa" type="xs:NCName"/>
    <xs:element name="status" type="xs:NCName"/>
    <xs:element name="jurusan" type="xs:string"/>
    <xs:element name="teknisi">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="namateknisi"/>
                <xs:element ref="alamat"/>
                <xs:element ref="kontak"/>
                <xs:element ref="jk"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="tl"/>
                <xs:element ref="email"/>
                <xs:element ref="umur"/>
                <xs:element ref="jabatan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="namateknisi" type="xs:NCName"/>
    <xs:element name="satpam">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="alamat"/>
                <xs:element ref="kontak"/>
                <xs:element ref="jk"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="tl"/>
                <xs:element ref="email"/>
                <xs:element ref="umur"/>
                <xs:element ref="jabatan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pemilikkantin">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="alamat"/>
                <xs:element ref="kontak"/>
                <xs:element ref="jk"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="tl"/>
                <xs:element ref="email"/>
                <xs:element ref="umur"/>
                <xs:element ref="hobi"/>
                <xs:element ref="beratbadan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hobi" type="xs:NCName"/>
    <xs:element name="beratbadan" type="xs:string"/>
    <xs:element name="alamat" type="xs:NCName"/>
    <xs:element name="jk" type="xs:NCName"/>
    <xs:element name="agama" type="xs:NCName"/>
    <xs:element name="pekerjaan" type="xs:string"/>
    <xs:element name="tl" type="xs:NCName"/>
    <xs:element name="email">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern value=".+@gmail.com"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="kontak" type="xs:integer"/>
    <xs:element name="umur" type="xs:string"/>
    <xs:element name="jabatan" type="xs:NCName"/>
    <xs:element name="nama" type="xs:NCName"/>
</xs:schema>

=== achmadf23/Tugas_2-/Pendidikan.xml
<?xml version="1.0" encoding="UTF-8"?>
<loginstaffpendidikan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pendidkan.xsd">
	<dosen>
		<namadosen>Rizki</namadosen>
		<nikdosen>11223344</nikdosen>
		<alamat>Cijerokaso</alamat>
		<kota>Bandung</kota>
		<jk>Laki-Laki</jk>
		<agama>Islam</agama>
		<pekerjaan>dosen</pekerjaan>
		<tl>Bandung</tl>
		<email>rizkilex@gmail.com</email>
		<kewarganegaraan>Indonesia</kewarganegaraan>
		<tahunkerja>2014</tahunkerja>
	</dosen>
	
	<mahasiswa>
		<namamahasiswa>Ahmad</namamahasiswa>
		<alamat>bandung</alamat>
		<kontak>082209096767</kontak>
		<jk>laki-laki</jk>
		<agama>islam</agama>
		<status>mahasiswa</status>
		<tl>Jakarta</tl>
		<email>achmad@gmail.com</email>
		<umur>18 th</umur>
		<jurusan>Teknik Informatika</jurusan>
	</mahasiswa>
	
	<teknisi>
		<namateknisi>Fahmy</namateknisi>
		<alamat>SetiaBudi</alamat>
		<kontak>082109097665</kontak>
		<jk>laki-laki</jk>
		<agama>islam</agama>
		<pekerjaan>anggota teknisi</pekerjaan>
		<tl>Subang</tl>
		<email>fahmy@gmail.com</email>
		<umur>23 th</umur>
		<jabatan>teknisi</jabatan>
	</teknisi>
	
	<satpam>
		<nama>Jayson</nama>
		<alamat>sarijadi</alamat>
		<kontak>0823454321</kontak>
		<jk>laki-laki</jk>
		<agama>islam</agama>
		<pekerjaan>satpam</pekerjaan>
		<tl>Makasar</tl>
		<email>jayson@gmail.com</email>
		<umur>50 th</umur>
		<jabatan>satpam</jabatan>
	</satpam>
	
	<pemilikkantin>
		<nama>Sindra</nama>
		<alamat>sarimanah</alamat>
		<kontak>082785635225</kontak>
		<jk>perempuan</jk>
		<agama>islam</agama>
		<pekerjaan>pengusaha</pekerjaan>
		<tl>bandung</tl>
		<email>sindraimoet@gmail.com</email>
		<umur>35 th</umur>
		<hobi>memasak</hobi>
		<beratbadan>75 kg</beratbadan>
	</pemilikkantin>
</loginstaffpendidikan>
